version: '3.4'

services:
  auth:
    image: ${DOCKER_REGISTRY}auth
    build:
      context: .
      dockerfile: API\Auth\Dockerfile

  storage:
    image: ${DOCKER_REGISTRY}storage
    build:
      context: .
      dockerfile: API\Storage\Storage\Dockerfile

